### PR TITLE
Add package.json#main field

### LINKED ISSUE #73: Cannot use import statement outside a module when importing this package using Jest
- Follow [the recommended steps to configure Jest to run though Typescript](https://jestjs.io/docs/getting-started#using-typescript)
- Create a file where you create a function that uses an imported function from `"tiny-secp256k1"` 
- Create a spec file where you import the function you created above
- Run `jest` 

This results in the following error

```js
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { compare } from "uint8array-tools";

SyntaxError: Cannot use import statement outside a module

import { pointMultiply, pointAdd } from "tiny-secp256k1";
^
```

It seems the `compare` import from `"uint8array-tools"` is the culprit here

Downgrading to version `1.1.6` resolves the issue

Happy to create a repro or help out if necessary

### PR DESCRIPTION
**Pull request by Robin-Hoodie**
Resolves #73

### CODE REVIEW

**Comment by junderw** [comment]
I understand moving to a hybrid model using only exports broke jest.

But I am worried that moving from hybrid exports to hybrid exports + main with cjs might break other tools besides jest causing more problems.

If you could try a few popular things using each of their latest versions (tools, bundlers, test suites etc.) to make sure this doesn't break them I'd appreciate it.

**Comment by Robin-Hoodie** [comment]
@junderw I've created a consumer repo here: https://github.com/Robin-Hoodie/tiny-secp256k1-consumer

I've added Babel,  TypeScript & Jest

Babel & TypeScript compilation continue to work

Running w/ Jest still fails, but now fails in the `uint8array-tools` code where the ESM module is also loaded instead of the CommonJS module. I've noticed that repo (which you also seem to be the author of) is also lacking a `main` field though, so it would probably be best that I add the `main` field in there as well.

Are there any other tools apart from the 3 above you were thinking of?

To try it out yourself, you need to:

- clone https://github.com/Robin-Hoodie/tiny-secp256k1-consumer & build it locally
- add the path to the local repo in package.json#dependencies#tiny-secp256k1-updated
- run `yarn:updated:ts` and/or `yarn:updated:babel` and/or `yarn updated:test`

**Comment by Robin-Hoodie** [comment]
Any feedback @junderw ?

**Comment by junderw** [comment]
Published as v2.2.1

uint8array-tools as v0.0.7

**Pull request merged**
