### PR TITLE
fix isPoint inconsistency with native library

### PR DESCRIPTION
**Pull request by dcousens**
Two things:

- [ ] We need more tests (adding in this PR)
- [ ] We need to be ensuring external modules run their unit tests in both a native and forced JS environment

The elliptic point that passes with `isPoint`, throws immediately in `decodeFrom` (and therefore isn't usable for any ECDSA operations).

### CODE REVIEW

**Comment by dcousens** [comment]
(note: this is not a fix for https://github.com/bitcoinjs/tiny-secp256k1/issues/6)

**Comment by fanatid** [comment]
@dcousens any idea why elliptic throws error? code in library looks valid, but this is not work... `(y**0.5)**2 != y` (?)
```js
  var y2 = x.redSqr().redMul(x).redIAdd(x.redMul(this.a)).redIAdd(this.b);
  var y = y2.redSqrt();
  if (y.redSqr().redSub(y2).cmp(this.zero) !== 0)
    throw new Error('invalid point');
```

**Comment by dcousens** [comment]
@fanatid the tl;dr is we used to have `curve.validate` **AND** `ECPoint.decodeFrom`,  but `secp256k1` native doesn't have the two,  it merges them.

Therefore,  we need to do the equivalent of `curve.validate` too.
See https://github.com/bitcoinjs/bitcoinjs-lib/blob/f4caaf42e7b58332d74c1540f88bcda7e55b82e6/src/hdnode.js#L107-L112

**Comment by fanatid** [comment]
Just realized that sqrt can give 2 numbers, so probably valid code should be:
```js
  var y2 = x.redSqr().redMul(x).redIAdd(x.redMul(this.a)).redIAdd(this.b);
  var y2c = y2.redSqrt().redSqr();
  if (y2c.redSub(y2).cmp(this.zero) !== 0 && y2c.redNeg().redSub(y2).cmp(this.zero) !== 0)
    throw new Error('invalid point');
```

@dcousens does this fix make sense? should we fix `elliptic`?

**Comment by fanatid** [comment]
I have no idea currently what give to us check `(y^0.5)^2 = y` (which generate `invalid point` error) in current code...

**Comment by dcousens** [comment]
@junderw interestingly it shows me force pushing on GitHub now! :tada:

**Comment by dcousens** [comment]
Any review?

**Pull request merged**
