### PR TITLE
fix: removed dep from `window` object

### LINKED ISSUE #111: remove dependancy from `window` object on browser
currently this package cannot be used in a service worker on the browser because we don't have access to the `window` object in the service worker. 

there is only 1 place in the codebase where we use `window` object, which is for the crypto package. 

we could fix this by directly using the crypto package and skipping `window` entirely. 

would love to work on this. will raise a PR soon

### PR DESCRIPTION
**Pull request by shamoilarsi**
closes #111

### CODE REVIEW

**Comment by landabaso** [comment]
Why not consider an approach like this instead?

```javascript
if (typeof crypto === 'undefined') {
  throw new Error('The crypto object is unavailable. This may occur if your environment does not support the Web Cryptography API.');
}
crypto.getRandomValues(bytes);
```

By directly referencing `crypto`, the correct scope (`window` or `self`) will be selected based on the environment. This could remove the necessity of using a separate crypto package, while still ensuring we have the required functionality available.

**Comment by junderw** [comment]
NACK on adding crypto-js as a dep.

Since it's the entire PR, basically, I'm tempted to close unless you can come up with something better.

**Comment by shamoilarsi** [comment]
@junderw will try a different approach. converting the PR to draft till then

**Comment by shamoilarsi** [comment]
@landabaso yep that makes sense. I wasn't aware the Web Crypto API had this function already (in hindsight it was being already used by `window` which should have been clear, my bad)

**Comment by shamoilarsi** [comment]
@landabaso yep that makes sense. I wasn't aware web workers have a crypto package as well which can be called with `self`. thanks for the help :D

**Comment by junderw** [comment]
Please rebase. It will fix the broken CI test.

**Comment by junderw** [comment]
Published as v2.2.2

**Pull request merged**
